### ISSUE TITLE
It would be nice that we can have rectangle shaped nodes instead of circles.

### ISSUE THREAD

**Issue by kodi** [flipio/GraphBuilder#1]
Circles should still be default ones, but it would be nice to have some kind of nodeRenderFactory that will be able to handle multiple shapes of nodes.

So far rectangle and circle will suffice, with circle being default shape (if not specified or invalid type provided)

**Comment by flipio** [comment]
Implemented for node type: 'square'.

Commit: 2a9d242084b5ccf65862ad7db6d94894e7960a29
